- name: "Reading user informations"
  read_csv:
    path: /home/ubuntu/users.csv
  register: usersList

- name: create access key for
  iam:
    iam_type: user
    name: "{{ user.name }}"
    state: present
    password: "{{ lookup('password', 'credentials/password length=12 chars=ascii_letters,digits') | password_hash('sha512') }}"
    groups: "{{ user.group }}"
    access_key_state: create
  loop: "{{ usersList.list }}"
  loop_control:
    loop_var: user
